### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by nicolasmaia** [wchen342/ungoogled-chromium-android#1]
As soon as is feasible, it would be good to have this on F-Droid as well.

@thermatk and @rudloff might be interested in this.

**Comment by wchen342** [comment]
I think it will be relatively hard to pass f-droid's policy for now since there are still quite a lot google dependencies. The most significant parts are some binaries in building tools, and the denpendencies on play services.
I believe the Bromite authors had the same problem so they set up their own repo, but if those dependencies can be completely removed then sure we can add this to f-droid.

**Comment by csagan5** [comment]
The biggest issue was to build the massive Chromium codebase with F-Droid build system; you can start reading from https://github.com/bromite/bromite/issues/4

There is also https://gitlab.com/fdroid/fdroiddata/merge_requests/3351 which was started because Bromite was not on F-Droid and without the binaries you mentioned.

**Comment by wchen342** [comment]
I have read both and the VM problem is really a pain. The whole approach looks messy to me and their Debian is two major versions back so I am not sure it is a good idea to put effort into that.

I have already cleaned out most of the binaries in build tools, but the jar/aar dependencies are still a problem. I shall begin import patches from that build you mentioned soon but I need to setup a debug environment first.

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/1](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/1)
