### ISSUE TITLE
'auto hide status bar' feature

### ISSUE THREAD

**Issue by DI555** [wchen342/ungoogled-chromium-android#13]
i would like to suggest optional feature 'auto hide system (notification) bar'.
(system (notification) bar appears by the swapdown on the upper border of the screen).
i saw this feature in total commander(android) first (you may see how it greatly works in tc), and find this highly useful!
would be very appreciate for this feature, even if it'll be switching only by the flags system!

**Comment by wchen342** [comment]
Do you mean automatically hide the adress bar like Firefox?

**Comment by DI555** [comment]
oh, sorry, i missdiscribe it, it's android status bar!
https://us.v-cdn.net/5019960/uploads/editor/im/jfqzfsypdgbt.png

**Comment by wchen342** [comment]
The only way to hide status bar for an app is to go fullscreen. You can make a specific site opened fullscreen in chromium by add the page to home screen. It will require some dramatic change to UI design if you want to make it auto because then the app needs to toggle between fullscreen and normal mode constantly, and it can interfere with, e.g. video play.

If someone contributes a patch for this in the future then I am happy to merge it. For now it will be considered a low priority task.

**Comment by Poopooracoocoo** [comment]
>(system (notification) bar appears by the swapdown on the upper border of the screen).

this implies that it isn't automatic. This just sounds like regular immersive mode (if I remember the name correctly). Your wording was strange though. By "swapdown" you meant swipe down and by "upper border" you meant top. This sounds like an easier request.

**Comment by wchen342** [comment]
Moved to https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/13
