### ISSUE TITLE
Decrypt password database/--disable-machine-id --disable-encryption doesn't work

### ISSUE THREAD

**Issue by drogga3** [wchen342/ungoogled-chromium-android#14]
I'm currently trying to copy Saved password database (Login Data) from ungoogled-chromium Windows to Android and executing adb shell 'echo "--disable-machine-id --disable-encryption" > /data/local/chrome-command-line'

I have verified the flags are enabled in chrome://version, but new passwords I save on ungoogled-chromium are still encrypted.

EDIT: My bad, those flags are currently Windows only.

**Comment by wchen342** [comment]
I checked the original issue ([https://github.com/Eloston/ungoogled-chromium/issues/444](https://github.com/Eloston/ungoogled-chromium/issues/444)) and it seems chrome only encrypt things on Windows. I suspect why it didn't work is because user data storage on Android is different from that on desktop systems but I need to inspect further.

**Comment by wchen342** [comment]
Moved to https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/14
