### ISSUE TITLE
Add StartPage to list of search providers

### ISSUE THREAD

**Issue by Poomex** [wchen342/ungoogled-chromium-android#16]
It would be great to have the option to search using https://www.startpage.com/, which is often considered more private than DDG.

**Comment by wchen342** [comment]
I will add it with next release.

**Comment by r-a-y** [comment]
Is it possible to use POST for the search instead of the default GET?  StartPage supports POST form submission as does DuckDuckGo.

POST is better for privacy as the search term is not leaked in the URL, which can be obtained from the referer when clicking on a search term.

Opera Desktop appears to be the only Chromium-based browser that allows for POST, from what I've observed so far.  I haven't tested Opera on Android yet.

**Comment by wchen342** [comment]
`POST` doesn't seem to be supported. Otherwise it is resolved by https://github.com/wchen342/ungoogled-chromium-android/commit/c0b185845bf00ff75430a90dfc03f28c9e3584fe.
