### ISSUE TITLE
Do you plan to show extension items in the menu?

### ISSUE THREAD

**Issue by ghost** [wchen342/ungoogled-chromium-android#33]
Click the icon on the right side of the address bar.
Do you plan to show extension items in the displayed list?

Some extensions such as stylus can only be set from there.

**Comment by wchen342** [comment]
Some time in the future hopefully, but these UI modifications takes a lot of time so it will not happen immediately.

**Comment by eklavya002** [comment]
> Some time in the future hopefully, but these UI modifications takes a lot of time so it will not happen immediately.

that means for element picking through ublock origin,we have to wait longer.

**Comment by wchen342** [comment]
> element picking through ublock origin

This specific function will require even more modifications if not impossible at all. Android+touchscreen is very different from native windows+mouse pointer and I suspect this function will require adaptation of the whole developer tools.

**Comment by ghost** [comment]
In kiwibrowser, the extension item is displayed.
Is it impossible to reference the kiwibrowser code?

**Comment by eklavya002** [comment]
> > element picking through ublock origin
> 
> This specific function will require even more modifications if not impossible at all. Android+touchscreen is very different from native windows+mouse pointer and I suspect this function will require adaptation of the whole developer tools.

i want to say the extension interface like this...
![Screenshot_20200604-160855](https://user-images.githubusercontent.com/61374684/83747141-d1405b00-a67d-11ea-89e6-710901736902.png)

**Comment by wchen342** [comment]
@eklavya002 That's not the picker, only the extension page itself.
@moon1618 Kiwi is a mixture of multiple versions of chromium so it's very difficult to know what exact change is made from source.

**Comment by eklavya002** [comment]
![Screenshot_20200604-160855~2](https://user-images.githubusercontent.com/61374684/83781347-019eee00-a6ac-11ea-8e11-3816b05be2bc.png)
I use this one to pick elements.

**Comment by eklavya002** [comment]
not the long press element picker (was on firefox) or desktop right click element pick.

**Comment by eklavya002** [comment]
As per your plan ,are u considering to implement same function as kiwi like extension interface(shown above) for cosmetic filtering and element pickup, 3 dot menu for extensions.

**Comment by wchen342** [comment]
So how does it work in action? How does the picker select elements if not by long-press or similar gestures?

**Comment by wchen342** [comment]
I will add the menu items leads to the extension pages as you mentioned above. But (programmatically) that interface and sth like element picker are different things. They do not come together.

**Comment by eklavya002** [comment]
> So how does it work in action? How does the picker select elements if not by long-press or similar gestures?

I don't understand these two things are different or same first case go to desktop right click and popup appers for element pickup 2nd case go to kiwi then extension interface click pick element then whole page greyed out then we pick element. please clarify

**Comment by eklavya002** [comment]
![Screenshot_20200604-215507](https://user-images.githubusercontent.com/61374684/83785141-82f78000-a6ae-11ea-89fa-33c9db574639.png)

**Comment by eklavya002** [comment]
![IMG_20200604_215421](https://user-images.githubusercontent.com/61374684/83785264-ae7a6a80-a6ae-11ea-997e-f143dbf4a267.jpg)

**Comment by wchen342** [comment]
You are looking at it from a user perspective and from your experience yes, you just need to click on the button and "magically" the picker shows up and you just need another click to select an element. But internally the program doesn't work that way.

The extension setting page and something that can pickup an element inside webpage belongs to two different component of the web browser, and on desktop they are bridged together through native codes. Now on mobile, the extension page itself exists but the interface is lacking, so if you want to show it the UI needs to be added. Then, in order to be able to pick something from a webpage, the same tool you used to pickup elements on desktop (presumably the same as developer tools) needs to be ported to mobile, which at least doesn't have a UI on mobile yet. And finally a bridge again needs to be created between these two components.

These are the works that needs to be done to implement such a function. It is not just adding several lines of codes.

**Comment by eklavya002** [comment]
> You are looking at it from a user perspective and from your experience yes, you just need to click on the button and "magically" the picker shows up and you just need another click to select an element. But internally the program doesn't work that way.
> 
> The extension setting page and something that can pickup an element inside webpage belongs to two different component of the web browser, and on desktop they are bridged together through native codes. Now on mobile, the extension page itself exists but the interface is lacking, so if you want to show it the UI needs to be added. Then, in order to be able to pick something from a webpage, the same tool you used to pickup elements on desktop (presumably the same as developer tools) needs to be ported to mobile, which at least doesn't have a UI on mobile yet. And finally a bridge again needs to be created between these two components.
> 
> These are the works that needs to be done to implement such a function. It is not just adding several lines of codes.

So basically as user i can block domain from adblocker setting page but can't pick from webpage( wait for future releases )? thanks a lot for simplifying these complexed things

**Comment by wchen342** [comment]
> i can block domain from adblocker setting page but can't pick from webpage

Yes, once I added the buttons for extenstions you will be able to access the setting page directly at least.

Thanks for the understanding.

**Comment by Madis0** [comment]
One thing that is also important but should be easier to include - a menu item for opening `chrome://extensions` itself.

**Comment by sivuda** [comment]
Would like this feature or atleast an alternate way to select extensions so I can use umatrix

**Comment by ghost** [comment]
Do you also check sites like this?
Is it helpful?
https://chromium-review.googlesource.com/c/chromium/src/+/2222773

**Comment by wchen342** [comment]
So it is linked to this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1074710.

It seems the developer of Kiwi made a feature request to chromium asking for merging the change in their patches. The dev team from chromium hasn't officially replied yet but the work in underway, which leads to the patch you mentioned. The patch itself is only a series of changes in gn flags to enable extension in content shell (for web tests, mostly for blink I suppose).

Now the problems become how fast they will accept this and implement the whole thing. If they will eventually make an official version of extension then I should leave the work to them, since my availability is limited and I want to make sure I'm not wasting efforts.

Anyone familiar with chrome/chromium development cycles please advise. Also @csagan5 @jstkdng @Eloston

**Comment by jstkdng** [comment]
I doubt chromium upstream will add those changes as that would empower chrome users to install ad-block into their phones and thus threatening google's source of income which would in turn threaten chromium maintainers' jobs.
What is stopping you from just using those patches here @wchen342 ?

**Comment by wchen342** [comment]
@jstkdng Yeah that's what happened before but we don't know whether it will change or not, although I also kind of doubt it could happen.
The problem is the extension is a huge patchset and takes a lot of time to maintain, and now I have a long list of [other enhancements and bugs to fix](https://github.com/wchen342/ungoogled-chromium-android/projects/1#column-9528128), so if they will do the job then I can focus on things that are more closely related to core functionalities of `ungoogled-chromium`.

**Comment by wchen342** [comment]
Moved to [https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/33](https://git.droidware.info/wchen342/ungoogled-chromium-android/issues/33)
