### ISSUE TITLE
is it possible to use Ungoogled Chromium as Android System WebView?

### ISSUE THREAD

**Issue by deepsweet** [wchen342/ungoogled-chromium-android#7]
Bromite:

* [Installing SystemWebView](https://github.com/bromite/bromite/wiki/Installing-SystemWebView)
* [Magisk module](https://github.com/Magisk-Modules-Repo/bromitewebview)

**Comment by wchen342** [comment]
I will try to release WebView builds with next version. I have no idea how to write a Magisk module though, so I guess you will need root to install it.

**Comment by dimqua** [comment]
@wchen342 could you also add a version of arm64 build for Android 5.0 and above? It weights significally less.

**Comment by wchen342** [comment]
@dimqua Do you need to run it on Lollipop or just want a smaller apk? Because some of the patches assume API level is above 24 (Nougat) so they won't work on Lollipop devices.

**Comment by wchen342** [comment]
@deepsweet The new version is released. Please test whether the WebView works and report back, thanks!

**Comment by deepsweet** [comment]
will try to go by myself through 2 links I provided above – so far it looks like `com.android.webview` is not allowed on my system.

>You can install Bromite SystemWebView only if the above output contains a packagename="com.android.webview" without a corresponding E: signature block, and if there is no com.android.webview package already installed.

not sure yet if Magisk approach allows to bypass this limitation, need to read that module source.

**Comment by wchen342** [comment]
Looks like Magisk module has the same limitations. I did some test and the article on Bromite wiki is basically right, that changing package name won't help in this case and if you are not running a custom ROM then your only option will be trying the method under the "Installation without root" section.

**Comment by dimqua** [comment]
It works for me (LineageOS 16.1). @wchen342 could you also add the apk to your f-droid repository?

**Comment by wchen342** [comment]
@dimqua Uploaded.

**Comment by deepsweet** [comment]
got it working as a normal userspace app with [AnyWebView](https://github.com/neoblackxt/AnyWebView) xposed module. thanks!

**Comment by dllud** [comment]
Hi @wchen342,

Thanks for the great work around here.

[Replicant](https://replicant.us) is planning to make one more release of Replicant 6 very soon. Right now the major blocker is finding a way to [update it's old WebView apk](https://redmine.replicant.us/issues/1780) for something that is in line with the [Free System Distribution Guidelines (FSDG)](https://www.gnu.org/distros/free-system-distribution-guidelines.html).

Guix (a FSDG compliant distro) distributes ungoogled-chromium after running it through a [build recipe that removes a few extra files](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/chromium.scm#n75). They are [confident that this approach renders them a fully free Chromium build](https://lists.gnu.org/archive/html/help-guix/2019-04/msg00225.html).

Replicant is thus considering a similar approach based on your ungoogled-chromium-android:
1. grab ungoogled-chromium-android
2. pass it through the Guix filters
3. make it output a WebView apk.

In this regard, I have some questions where your input would be much appreciated:
1. Do you have instructions somewhere on how to build the WebView apk?
2. Which of your patches assume API 24? Are they easy to revert/rework for API 23? (Replicant 6 only provides API 23.)

**Comment by wchen342** [comment]
@dllud Thanks for your interest in this project!

I'm not an expert in free softwares but I think ungoogled-chromium-android in its current state is not yet FOSS. Unlike Linux builds, Android builds require extra Java jar/aar packages, among some are proprietary (I removed all the Google Play/Service related ones but there may be some left). Also there are 3~4 binary files needed to build successfully and I haven't figured out how to get around those. I believe the Guix filters (and the ungoogled-chromium main project) only dealt with Linux-build files.

Of course if you still want to try make this completely FOSS I am open to suggestions and will be happy to discuss further.

About your questions:
1. You can find the building script in `build.sh`. It's a plain bash script and every command needed to build an Android version is inside it. `ninja` will build apk based on target provided which in the script I used `system_webview_apk`.
2. The patches assuming API 24 is for removing Google Play. I used API 24 because there are some logic that is different when API is >24 or not, and the >24 version is much simpler so I just went with 24. It should be possible to cover for API 23. Another problem, however, is I only tested my building script for `monochrome_public_apk` which is API 24, and lowering that to `chrome_modern_public_apk` which is API 21 may cause unknown problems (although for WebView this seems to be unrelated).

**Comment by herbsmn** [comment]
@wchen342 Thanks for your work on this. Can you list the binary files that you haven't figured out how to get around yet so we can see if the Guix filters remove them or not?

**Comment by dimqua** [comment]
Check it out guys:
https://gitlab.com/fdroid/fdroiddata/merge_requests/3351
https://gitlab.com/thermatk/Unobtainium

The author lose interest in this project, but you could probably use some of his patches to improve the situation.

**Comment by wchen342** [comment]
@herbsmn The files are
```
build/android/chromium-debug.keystore
third_party/bazel/desugar/Desugar-runtime.jar
third_party/icu/android/icudtl.dat
third_party/icu/android/icudtl_small.dat
third_party/icu/common/icudtb.dat
third_party/android_build_tools/aapt2/aapt2
```

@dimqua I am aware of the project but it was done when chromium was still v67 and now it's v77 so a lot of those patches no longer apply..

**Comment by dimqua** [comment]
@wchen342 is your f-droid repo currently working?

**Comment by wchen342** [comment]
@dimqua Thanks for the heads up. Obviously when I last rebooted the server it failed to start somehow. It is online now.
